version: '3.9'

services:
  #mongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  #Node API service
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      HOST: localhost
      DB_URI: mongodb://mongo_db:27017
      JWT_SECRET: 18a7fc5d87d650ed8438c2a968e788e58084bb397c3aeb4fb696732227ccbbcd
      PUBLIC_KEY: mypublickey
      SESSION_SECRET: mysessionsecretkey
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}